/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as EscenarioRouteImport } from './routes/escenario'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as SimuladorRouteImport } from './routes/simulador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const EscenarioRoute = EscenarioRouteImport.update({
  id: '/escenario',
  path: '/escenario',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/escenario': typeof EscenarioRoute
  '/metas': typeof MetasRoute
  '/pagos': typeof PagosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/escenario': typeof EscenarioRoute
  '/metas': typeof MetasRoute
  '/pagos': typeof PagosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/escenario': typeof EscenarioRoute
  '/metas': typeof MetasRoute
  '/pagos': typeof PagosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/calendario' | '/escenario' | '/metas' | '/pagos' | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendario' | '/escenario' | '/metas' | '/pagos' | '/simulador'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/escenario'
    | '/metas'
    | '/pagos'
    | '/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  EscenarioRoute: typeof EscenarioRoute
  MetasRoute: typeof MetasRoute
  PagosRoute: typeof PagosRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escenario': {
      id: '/escenario'
      path: '/escenario'
      fullPath: '/escenario'
      preLoaderRoute: typeof EscenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  EscenarioRoute: EscenarioRoute,
  MetasRoute: MetasRoute,
  PagosRoute: PagosRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
